language: java
jdk: openjdk8

addons:
  sonarcloud:
    organization: "microconfig"
    token: "cK1Bckt4dGRsKbUac9lR4ywq4ecBCOKqnvf581AP4LEjuWQ0EkoRShwIovPWj/F1LkN8mNi2Pgq9TTvGduUTpm745LFw/o/3tYPhTjoWpHr9PTrIvlBYbRx5rcj1qNA0WRBzeCzahdwQ7QxFAoTxyNB/KWhquEUkCONEERHCo7H7E2eJPyDYE8cf4a2Pi91wZs8OdGJGZ4k6ZfHIaXNo91bm7my9cHxKr9hDxEfOEq3HIfByjPPG+xvYtdk2qKSxSQpoPyk4QyvJhVG89seDMHOH0CepgbonI0fvwVIBg0zqpRts73K0cqaAKB7i/ZpO9Ch6Hkfq1yqKAdxeOMKXR8AH9Zfl+IKJoR0xenGVtgTIBhhms2bI2iWmmyHJMb0NCIEhb+0P1yUiSBPkJ32Stmkq8MHDF52kkp4A/IXmZhrD9L9fFP3x6qlZvzHXjyRRX0EInRI7zKFuY/X79j5Jt7MyZnkJYXAfTFUaUGJYgAtkw2/iqUgiyh1N5u1zJKOJ2//ev9pGd09cCl+H7q5YRYhd0SvsuQolWtMXQb3Q7pxhvlGzsgMPZWKo1Orz56zv100k2XBesuQTtoe02UbtbiVGgGU79yIquKIGJuBehjtHcDcAl7WVZjnGu4nb/fOSiOP4lw8y970g2BOCsA2wrcE5o6bWDdacsYupzhnwYQk="

script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
  - ./gradlew --stacktrace sonarqube