language: java
dist: trusty
jdk: openjdk8

addons:
  sonarcloud:
    organization: "microconfig"
    token:
      secure: "I7hhr8AALrNQUsEa//GXTkwOGfaJo+4a4yKcfhLXyV34kHNCe+wAVOf7Wt4kJ9+uy3pkqmQvgrHTq8EexVxDes1tET+d+EQek1PRx3EOdcOsRvIESoZAv2Rahgxz/w3Fpa8892LR7IbHpi4aDk3nlsrfw5QQVucrP4pNsCuq6JKfD04pDOHFEpJ5c6S7XdYMalFQ4IDxCv9/jZKvaFhpPOMzehpyTkQN/FeRRvWjzI9BGLDzojn/f627Z11IarYvGoaU79PraAxZrKeaavE7T1Qpoz4epVPUwwSo6cJZVu1uxZeu+n3GyxKB4Ui+wlFvaYVjG3bwR1osXRChkl0ATZo75mjnJfon+haMo7OTisYJJexvWwaScmnjPv5uUUHRR/qzzr2g350FXB+H8L25nR8xN//UvFBCONUqAtb0Y7mjykP3aSbpPX3eROrV8uW9p0Xl8QMLiM1SYf2R4ffSmHUCoRCamBWnPz6OIi3xnAx4N6NuBu+TiU5fK7lv5m4VnsUklNSeNz7Yvw95lWTDX86f+wdoRo/7t0v1OZR1FSfvnt3YDMdZtkHbILyAwEBIWADFMD7uQHldMfGgzl44Q054OpMc0zObBPufnsW9Tdd/IpgnZxqEbI/EenlEMzSadZNspPAdO+RXRO+rbFr2E+VdN1HWsuei6OFdMHxPfA4="

script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
  - ./gradlew --stacktrace sonarqube