language: java
dist: trusty
jdk: openjdk8

addons:
  sonarcloud:
    organization: "microconfig"
    token:
      secure: "gcqaIy/0DFDZfrbA4bDx5oirzukYZo8WILPkUCr9Sg85PtkUJFajtIYZpu/rNhXMnOklFd2++L/h62G2s2fWXgimqEoB9PNPg6Gc78ACZcZrOaPEEtW9vnJStt7HylRIhvF03CZrSP8Eco9DEPKcgo6f81+b+xSLXs9x/veWa49QwL7GbaVKkNBsdvaiBVkIK1teiP4J+go7IATKxq6XTMMLdnQU8fUlaxGPJj6QLgbGwCcH+o+TOWIJ5exmD5ub97jDE1JtAzMpugl6FxIIsT5TtXxdAqy75Ar8vapnlzYLVTGHv8RESu9/udfEK5OGWzWYKeB7Zb7wkOkpjYmh4bk2JjArv3CMjK05pG5l833eUUbiphHVx2Ezict1t5QTXTK2DUKLsZ8o6SOXNwh5IIaIq1XCA2ggvhMTroWY6BWIwrMbeVPGUZQYIglMZeTguCf4m1dA5qlLUL7c7g6FxoRQ4hwERMfIRt9uMa8ExGwTwv3yZ1I+SpP9CVLpvv6U8vXQ80XZ6MFhavoiMmpPj8P3x00pBGqokexJSpOpGYqz3Wkmhsmcvv3tcJn9bsYylyutsqF52vyVsevlab1EpfYxwqUbyqEnSHUtJPn+3iFoNC0nicQ6vEUgqe6y5pi5LF/ZOFKAVZ0FGwsKcngx05qIk86zlXcRI9UqTrZ0MGw="

script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
  - ./gradlew sonarqube