language: java
jdk: openjdk8

addons:
  sonarcloud:
    organization: "microconfig"
    token: "lShDXJRxMnJSyWmDda8CXuF9E1welNI0Txx5Dnc521Pr2B9DGoBIoI6LTsnXEny3tsMKYuhxhVils4t+yCx9gg/WK98XD34Y1NjQtYij54yHBaWnDFPMdc3SFTHtop6XgAwuwE6ePY0cSIov/SMtBkIkD7PgtW5lBVz3zhsPEoFDs/b5izJP9RW2MXIN9dAL3lFHnFfaKadC7Z2AjcXxfU7ZWbY1bUGy962SXxB6yrjzttyJNa+ribOmKNimUf5hDwqSAlH/92Z/0xRKFEpj24Xhd1er1vWrPSrYI549exHJ2OrFkHq4xv1s1jLvnZ9Yxwov2W88Ll8xg6xEkwqYiX/uxvODIKTmIpUcJ7I0Z0liM0w6dDYL9CJ34/cnzZDFIngDOWGcp+6rp3Uc0CliITzRsi5rQoQWObXWdjJLRRAulpGjqfSvVuhENgUjIPnrgg0gGbruIjAsEJmd+tlAsuKmdz3jVwHYIWwZgaJEe9fZ1i+M9fvO1odLY0Ctunx0M9NJthouZ6SqOOP7VbRKRMQGFmGvPiZoAq86SAliW6s1eYUCjQVp1e/n6HxSVBdX/IhJY5bHbl66NPDFRojCr459Buc8BPN3lATqNTtamgNudURxlWVeFKM78QHQilWH5XdRZtGmG1mZn3XZrGsXWFtbUsh5zKbWpimLFFADdJI="

script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
  - ./gradlew --stacktrace sonarqube