FROM ghcr.io/graalvm/native-image:muslib-22 AS builder

WORKDIR /

ADD microconfig.jar /microconfig.jar
RUN native-image --static --libc=musl -jar /microconfig.jar
RUN /microconfig -v

ENTRYPOINT cp /microconfig /volume/microconfig