name: "Build Native Binary"

on:
  push:
    branch: [native-binary]

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build Jar"
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Jar
        run: ./gradlew shadowJar
      - name: Rename Jar
        shell: bash
        run: mv microconfig-cli/build/libs/microconfig-cli-*-all.jar microconfig-cli/build/libs/microconfig.jar
      - uses: actions/upload-artifact@v2
        with:
          name: microconfig.jar
          path: microconfig-cli/build/libs/microconfig.jar

  linux:
    name: "Build Linux"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Jar
        uses: actions/download-artifact@v2
        with:
          name: microconfig.jar
      - name: checkout
        uses: actions/checkout@v2
      - name: ls
        shell: bash
        run: ls -lh
#      - name: Install GraalVM Native Image
#        shell: bash
#        run: .github/scripts/native/graalvm-linux.sh
#      - name: Build Binary
#        shell: bash
#        run: .github/scripts/native/native.sh
#      - uses: actions/upload-artifact@v2
#        with:
#          name: microconfig-linux
#          path: ./microconfig

#  windows:
#    name: "Build Windows"
#    needs: build
#    runs-on: windows-2016
#    steps:
#      - name: Download Jar
#        uses: actions/download-artifact@v2
#        with:
#          name: microconfig.jar
#      - name: checkout
#        uses: actions/checkout@v2
#      - name: Install GraalVM Native Image
#        shell: bash
#        run: .github/scripts/native/graalvm-win.sh
#      - name: Build Binary
#        shell: bash
#        run: .github/scripts/native/native.bat
#      - uses: actions/upload-artifact@v2
#        with:
#          name: microconfig-windows
#          path: microconfig.exe
#
#  macos:
#    name: "Build MacOS"
#    needs: build
#    runs-on: macos-latest
#    steps:
#      - name: Download Jar
#        uses: actions/download-artifact@v2
#        with:
#          name: microconfig.jar
#      - name: checkout
#        uses: actions/checkout@v2
#      - name: Install GraalVM Native Image
#        shell: bash
#        run: .github/scripts/native/graalvm-mac.sh
#      - name: Build Binary
#        shell: bash
#        run: .github/scripts/native/native.sh
#      - uses: actions/upload-artifact@v2
#        with:
#          name: microconfig-macos
#          path: ./microconfig
#