# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Windows Native Image

on:
  push:
    branches: [ binary ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install GraalVM Native Image
        shell: bash
        run: ./graalvm-win.sh
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Jar
        run: gradlew.bat shadowJar
      - name: Build Binary
        shell: bash
        run: graalvm/bin/native-image.cmd -jar microconfig-cli/build/libs/microconfig-cli-*-all.jar
      - uses: actions/upload-artifact@v2
        with:
          name: microconfig
          path: microconfig.exe